server:
  port: 8085
spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://slon.felk.cvut.cz:5432/gulineka
    username: gulineka
    password: gulineka_DBS212
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    urls:
      - name: api-system-cloud
        url: http://34.125.160.101:8081/v3/api-docs
      - name: api-core-cloud
        url: http://34.125.160.101:8089/v3/api-docs
      - name: api-notifications-cloud
        url: http://34.125.160.101:8082/v3/api-docs
