#!/bin/bash

cd backend/task-microservice
mvn clean install

cd backend/user-microservice
mvn clean install

cd backend/notification-microservice
mvn clean install

cd backend/discovery-server
mvn clean install

cd backend/api-gateway
mvn clean install

docker compose up --force-recreate --build -d

