web:
  build: .
  links:
    - "database_default"
  ports:
    - "8000:80"
  volumes:
    - ".:/app:rw"
    - "./data:/data:rw"
  command: python manage.py runserver 0.0.0.0:80
  env_file: .env-local

database_default:
  image: postgres:13.5-alpine
  environment:
    POSTGRES_DB: "db"
    POSTGRES_HOST_AUTH_METHOD: "trust"
    SERVICE_MANAGER: "fsm-postgres"
  volumes:
    - ".:/app:rw"