version: '3.8'
services:
  eureka-server:
    image: dockerspringgcp-discovery-server:0.0.1-SNAPSHOT
    build: backend/discovery-server
    ports:
      - 8761:8761
  api-gateway:
    image: dockerspringgcp-api-gateway:0.0.1-SNAPSHOT
    build: backend/api-gateway
    ports:
      - 8080:8080
    depends_on:
      - eureka-server
    environment:
      SPRING_APPLICATION_JSON: '{"eureka":{"client":{"serviceUrl":{"defaultZone":"http://eureka-server:8761/eureka"}}}}'
  user-service:
    image: dockerspringgcp-user-microservice:0.0.1-SNAPSHOT
    build: backend/user-microservice
    ports:
      - 8081:8081
    depends_on:
      - eureka-server
    environment:
      SPRING_APPLICATION_JSON: '{"eureka":{"client":{"serviceUrl":{"defaultZone":"http://eureka-server:8761/eureka"}}}}'
  task-service:
    image: dockerspringgcp-task-microservice:0.0.1-SNAPSHOT
    build: backend/task-microservice
    depends_on:
      - user-service
      - eureka-server
    environment:
      SPRING_APPLICATION_JSON: '{"eureka":{"client":{"serviceUrl":{"defaultZone":"http://eureka-server:8761/eureka"}}}}'
    ports:
      - 8089:8089
  notification-service:
    build: backend/notification-microservice
    image: dockerspringgcp-notification-microservice:0.0.1-SNAPSHOT
    depends_on:
      - task-service
      - user-service
      - eureka-server
    environment:
      SPRING_APPLICATION_JSON: '{"eureka":{"client":{"serviceUrl":{"defaultZone":"http://eureka-server:8761/eureka"}}}}'
    ports:
      - 8082:8082

  swagger-docs:
    build: backend/swagger-docs
    image: dockerspringgcp-swagger-docs:0.0.1-SNAPSHOT
    ports:
      - 8085:8085
    depends_on:
      - task-service
      - user-service
      - notification-service

  react-client:
    build: frontend/
    image: react-docker-gcp
    ports:
      - 3000:3000