#!/bin/bash

cd task-microservice/
mvn clean install

cd user-microservice/
mvn clean install

cd notification-microservice/
mvn clean install

cd discovery-server/
mvn clean install

cd api-gateway/
mvn clean install

