export const ADMIN_ROUTE = '/admin'
export const AUTH_ROUTE = '/auth'
export const PROJECT_ROUTE = '/project'
export const REGISTRATION_ROUTE = '/registration'
export const TODO_ROUTE = '/to-do'
export const USER_ROUTE = '/user'
export const TASK_ROUTE = '/task'